services:
  kpress-rabbitmq:
    image: rabbitmq:3.13
    container_name: kpress-rabbitmq
    ports:
      - "5552:5552"
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_stream advertised_host localhost
    command: >
      sh -c "
        rabbitmq-plugins enable rabbitmq_stream rabbitmq_stream_management &&
        rabbitmq-server
      "
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  kpress-db-user:
    image: postgres:latest
    container_name: kpress-db-user
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5

  kpress-app-user-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3031:3031"
    depends_on:
      kpress-db-user:
        condition: service_healthy
      kpress-rabbitmq:
        condition: service_healthy
