services:
  kpress-app-user-service:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3033:3033"
    depends_on:
      - kpress-db-user

  kpress-db-user:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"